<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ServiceGoogleSheetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
   
        public function run()
        {
            $services = [
                'Consulting Case Study Coaching',
                'Consulting Coaching with no case studies',
                'Software Development Engineering',
                'Coding Tests using Leetcode',
                'Data Analytics Questions Set 1 of 3',
                'Data Analytics Questions Set 2 of 3',
                'Data Analytics Questions Set 3 of 3',
                'Statistics Questions',
                'Tech Industry Questions',
                'Technology Sales Questions',
                'Product Management in Tech',
                'Technology Support Questions',
                'Python Training',
                'Private Equity Questions',
                'Venture Capital',
                'Investment Banking Questions Set 1 of 9',
                'Investment Banking Questions Set 2 of 9',
                'Investment Banking Questions Set 3 of 9',
                'Investment Banking Questions Set 4 of 9',
                'Investment Banking Questions Set 5 of 9',
                'Investment Banking Questions Set 6 of 9',
                'Investment Banking Questions Set 7 of 9',
                'Investment Banking Questions Set 8 of 9',
                'Investment Banking Questions Set 9 of 9',
                'Capital Markets General',
                'Capital Markets DCM',
                'Capital Markets ECM',
                'Global Markets - Trading & Investment Ideas',
                'Global Markets Equity Research',
                'Global Markets Credit Research',
                'Global Markets Fixed Income Sales Question Set 1 of 3',
                'Global Markets Fixed Income Sales Question Set 2 of 3',
                'Global Markets Fixed Income Sales Question Set 3 of 3',
                'Global Markets Equities Sales Question Set 1 of 3',
                'Global Markets Equities Sales Question Set 2 of 3',
                'Global Markets Equities Sales Question Set 3 of 3',
                'Global Markets Prime Brokerage Questions',
                'Global Markets Algorithmic Trading',
                'Global Markets Equities Derivatives Question Set 1 of 2',
                'Global Markets Equities Derivatives Question Set 2 of 2',
                'Global Markets Fixed Income Derivatives Question Set 1 of 2',
                'Global Markets Fixed Income Derivatives Question Set 2 of 2',
                'Global Markets Fixed Income Questions',
                'Global Markets Mortgage Backed Securities Questions',
                'Global Markets Fixed Income Rates Questions',
                'Global Markets Collateralized Loan Obligations Questions',
                'Global Markets Ratings Agency Questions',
                'Global Markets Fixed Income Leveraged Finance',
                'Global Markets Quantitative Finance Questions Set 1 of 3',
                'Global Markets Quantitative Finance Questions Set 2 of 3',
                'Global Markets Quantitative Finance Questions Set 3 of 3',
                'Global Markets Inter-Dealer Broking Questions',
                'Global Markets Convertible Bonds',
                'Global Markets Credit Derivatives',
                'Global Markets Equities Trading',
                'Global Markets Fixed Income Trading',
                'Asset/Investment Management Questions Set 1 of 3',
                'Asset/Investment Management Questions Set 2 of 3',
                'Asset/Investment Management Questions Set 3 of 3',
                'Asset/Investment Management Multi-management Questions',
                'Asset/Investment Management Passive-management Questions',
                'Asset/Investment Management Alternatives Questions',
                'Asset/Investment Management Marketing Questions',
                'Asset/Investment Management Emerging Markets Questions',
                'Wealth Management Questions',
                'MacroEconomic issues & Current Affairs',
                'Risk Management General Questions',
                'Risk Management Credit Risk Questions Set 1 of 2',
                'Risk Management Credit Risk Questions Set 2 of 2',
                'Risk Management Market Risk Questions',
                'Risk Management Regulatory Capital Questions',
                'Risk Management Operational Risk Questions',
                'Risk Management Credit Card Risk Questions',
                'Basic Finance Questions',
                'Basic Finance Questions',
                'Product Control in Finance Questions Set 1 of 3',
                'Product Control in Finance Questions Set 2 of 3',
                'Product Control in Finance Questions Set 3 of 3',
                'Middle Office Operations Questions 1 of 10',
                'Middle Office Operations Questions 2 of 10',
                'Middle Office Operations Questions 3 of 10',
                'Middle Office Operations Questions 4 of 10',
                'Middle Office Operations Questions 5 of 10',
                'Middle Office Operations Questions 6 of 10',
                'Middle Office Operations Questions 7 of 10',
                'Middle Office Operations Questions 8 of 10',
                'Middle Office Operations Questions 9 of 10',
                'Middle Office Operations Questions 10 of 10',
                'Middle Office General Questions Set 1 of 2',
                'Middle Office General Questions Set 2 of 2',
                'Technology in Finance Questions Set 1 of 5',
                'Technology in Finance Questions Set 2 of 5',
                'Technology in Finance Questions Set 3 of 5',
                'Technology in Finance Questions Set 4 of 5',
                'Technology in Finance Questions Set 5 of 5',
                'Compliance Questions',
                'Data Provider (Like Bloomberg, Reuters, Datastream)',
                'Investment Consulting Questions Set 1 of 2',
                'Investment Consulting Questions Set 2 of 2',
                'Real Estate Questions',
                'Real Estate Residential Questions',
                'Advertising',
                'Sales (General Sales and not Global Markets-related)',
                'Marketing Questions',
                'Engineering Mechanical',
                'Law UK Questions Set 1 of 7',
                'Law UK Questions Set 2 of 7',
                'Law UK Questions Set 3 of 7',
                'Law UK Questions Set 4 of 7',
                'Law UK Questions Set 5 of 7',
                'Law UK Questions Set 6 of 7',
                'Law UK Questions Set 7 of 7',
                'Assurance/Audit Questions Set 1 of 8',
                'Assurance/Audit Questions Set 2 of 8',
                'Assurance/Audit Questions Set 3 of 8',
                'Assurance/Audit Questions Set 4 of 8',
                'Assurance/Audit Questions Set 5 of 8',
                'Assurance/Audit Questions Set 6 of 8',
                'Assurance/Audit Questions Set 7 of 8',
                'Assurance/Audit Questions Set 8 of 8',   
                'Transaction Services  Questions Set 1 of 3',
                'Transaction Services  Questions Set 2 of 3',
                'Transaction Services  Questions Set 3 of 3',
                'Tax - UK Non-personal tax - Questions Set 1 of 4',
                'Tax - UK Non-personal tax - Questions Set 2 of 4',
                'Tax - UK Non-personal tax - Questions Set 3 of 4',
                'Tax - UK Non-personal tax - Questions Set 4 of 4',
                'Tax - UK Personal tax - Questions',
                'Actuarial Consulting Questions Set 1 of 4',
                'Actuarial Consulting Questions Set 2 of 4',
                'Actuarial Consulting Questions Set 3 of 4',
                'Actuarial Consulting Questions Set 4 of 4',
                'Actuarial Non-Life Questions Set 1 of 2',
                'Actuarial Non-Life Questions Set 2 of 2',
                'Insolvency Questions',
                'Management Accounting Questions',
                'Executive Compensation Questions',
                'Behavioral Question Set 1 0f 14',
                'Behavioral Question Set 2 0f 14',
                'Behavioral Question Set 3 0f 14',
                'Behavioral Question Set 4 0f 14',
                'Behavioral Question Set 5 0f 14',
                'Behavioral Question Set 6 0f 14',
                'Behavioral Question Set 7 0f 14',
                'Behavioral Question Set 8 0f 14',
                'Behavioral Question Set 9 0f 14',
                'Behavioral Question Set 10 0f 14',
                'Behavioral Question Set 11 0f 14',
                'Behavioral Question Set 12 0f 14',
                'Behavioral Question Set 13 0f 14',
                'Behavioral Question Set 14 0f 14',
                'Excel & Google Sheets training',
                'Career Planning',
                'Cold Call coaching - Making the call',
                'Be more charming',
                'Cover Letter by AI',
                'Sales Pitch for job interview by AI',
                'Cold Call Script by AI',
                'Your resume graded and analyzed by AI',
                'LinkedIn search to find the right professionals to network with',
                'Best networking Email ever',
                'Elevator Pitch - Selling yourself effectively',
                'Target companies Google Sheet',
                'Using Headhunters effectively',
                'What\'s wrong with your resume?',
                'Your achievements - Make them sound brilliant!',
                'Your achievements - Get our feedback so you can improve them',
                'Video interviews - How to do them properly',
                'Why I want to work for this company',
                'Why I want to work in this business area',
                'How to research your employer company before interview',
                'Networking Spreadsheet',
                'Applications Spreadsheet',
                'Companies Spreadsheet',
                '100 behavioral questions',
                'LinkedIn search to find the right people'
            ];
    
            foreach ($services as $service) {
                DB::table('service_googlesheets')->insert([
                    'service_name' => $service,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    
}
